services:
  web:
    build: .
    ports:
      - 80:80
    volumes:
      - ./config:/var/www/config/
      - ./apache.conf:/etc/apache2/sites-enabled/apache.conf
      - ./data/web:/var/www/
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://todoapp@postgres/todos
  postgres:
    image: postgres:9.6.2-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_DB: password