services:
  web:
    tty: true
    stdin_open: true
    build: .
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config:/var/www/config/
      - ./data/web:/var/www/html/
      - ./data/storage:/var/www/storage/